export const FRUIT_KEYWORDS = [
    "Hedgehog",
    "African Wild Dog",
    "Dalmatian",
    "Pelican",
    "Flamingo",
    "Mini Pig",
    "Peppermint Penguin",
    "Caterpillar",
    "Lion",
    "Irish Water Spaniel",
    "Tortuga De La Isla",
    "Crocodile",
    "Purple Butterfly",
    "Glacier Moth",
    "Puffin",
    "Goat",
    "Honey Badger",
    "Arctic Fox",
    "Kookaburra",
    "Jellyfish",
    "Sheeeeep",
    "Bald Eagle",
    "Many Mackerel",
    "Lion Cub",
    "Groundhog",
    "Alpaca",
    "Wood Pigeon",
    "Platypus",
    "Christmas Pudding Pup",
    "Ice Wolf",
    "Happy Clam",
    "Zombie Buffalo",
    "Turkey",
    "Llama",
    "Ice Cream Hermit Crab",
    "Slime",
    "Red Sand Dollar",
    "White Sand Dollar",
    "Orange Butterfly",
    "Hummingbird",
    "Snowball Pet",
    "Snow Monkey",
    "Royal Palace Spaniel",
    "Nautilus",
    "Royal Corgi",
    "Merry Mistletroll",
    "Lamb",
    "Ram",
    "Flaming Fox",
    "Orca",
    "Ghost Bunny",
    "Green Amazon",
    "Puptune",
    "Yeti",
    "Giant Blue Scarab",
    "Pomeranian",
    "Brown Springer Spaniel",
    "Black Springer Spaniel",
    "Hamster",
    "Horse",
    "Koala",
    "Space Whale",
    "Albino Bat",
    "Brown-Chested Pheasant",
    "St Bernard",
    "Giant Black Scarab",
    "Business Monkey",
    "Toy Monkey",
    "Panda",
    "Tan Chow-Chow",
    "Highland Cow",
    "Frog",
    "Wooly Rhino",
    "Pretty Pony",
    "Frostbite Cub",
    "Starmite",
    "Elasmosaurus",
    "Rooster",
    "Toasty Red Panda",
    "Nightmare Owl",
    "Evil Chickatrice",
    "Evil Basilisk",
    "Red Squirrel",
    "Indian Flying Fox",
    "Magma Moose",
    "Magma Snail",
    "Pumpkin Friend",
    "Winter Doe",
    "Deinonychus",
    "Sabertooth",
    "Partridge",
    "Headless Horse",
    "Fanghorn Tortoise",
    "Bauble Buddies",
    "Rice Cake Rabbit",
    "Peregrine Falcon",
    "Penguin",
    "Karate Gorilla",
    "Chef Gorilla",
    "Wildfire Hawk",
    "Burning Bunny",
    "Halloween White Skeleton Dog",
    "Gingerbread Reindeer",
    "Zombie Wolf",
    "Gingerbread Hare",
    "Blue Ringed Octopus",
    "Candy Cane Snail",
    "Scarlet Butterfly",
    "Sprout Snail",
    "Skunk",
    "Praying Mantis",
    "Inmate Capuchin Monkey",
    "Preppy Capuchin Monkey",
    "Albatross",
    "Puffer Fish",
    "Starfish",
    "Golden Jaguar",
    "Cold Cube",
    "Ribbon Seal",
    "Wyvern",
    "Deathstalker Scorpion",
    "Hydra",
    "Vulture",
    "Roadrunner",
    "Lionfish",
    "Floral Eggy",
    "Ornate Horned Frog",
    "Bee",
    "Sloth",
    "King Penguin",
    "Scarecrow Cat",
    "Shetland Pony White",
    "Toucan",
    "Gold Mahi Mahi",
    "Pine Marten",
    "Gingerbread Mouse",
    "Clownfish",
    "Seagull",
    "Pink Betta Fish",
    "Ladybug",
    "Water Rabbit",
    "Binturong",
    "Black Macaque",
    "Grave Owl",
    "Ginger Cat",
    "Corgi",
    "Salamander",
    "Robot",
    "Swordfish",
    "Alley Cat",
    "Grinmoire",
    "Red Crowned Crane",
    "Trapdoor Snail",
    "Komodo Dragon",
    "Spider Crab",
    "Lammergeier",
    "Black Kite",
    "Badger",
    "Shiba Inu",
    "Red Panda",
    "Mr Whiskerpips",
    "Ghost Chick",
    "Water Moon Bear",
    "Flower Power Duckling",
    "Lunar White Tiger",
    "Persian Cat",
    "Lunar Ox",
    "Bat Dragon",
    "Shadow Dragon",
    "Giraffe",
    "Frost Dragon",
    "Owl",
    "Parrot",
    "Diamond Butterfly",
    "Crow",
    "Evil Unicorn",
    "Balloon Unicorn",
    "Blazing Lion",
    "Arctic Reindeer",
    "Diamond Hummingbird",
    "Monkey King",
    "Turtle",
    "Albino Monkey",
    "Black-Chested Pheasant",
    "Diamond Amazon",
    "Hot Doggo",
    "Undead Jousting Horse",
    "Royal Mistletroll",
    "Kangaroo",
    "Strawberry Shortcake Bat Dragon",
    "Chocolate Chip Bat Dragon",
    "Haetae",
    "Pirate Ghost Capuchin Monkey",
    "Jekyll Hydra",
    "Cupid Dragon",
    "Frost Unicorn",
    "Candyfloss Chick",
    "Fairy Bat Dragon",
    "Mechapup",
    "Tió De Nadal",
    "Giant Gold Scarab",
    "Golden Hummingbird",
    "Sugar Glider",
    "Nessie",
    "Winged Tiger",
    "Caelum Cervi",
    "Aurora Fox",
    "Sugar Axolotl",
    "Glacier Kitsune",
    "Frost Fury",
    "Diamond Hamster",
    "Vampire Dragon",
    "Naughty Mistletroll",
    "Lava Dragon",
    "Diamond Albatross",
    "Emperor Gorilla",
    "Grim Dragon",
    "Hippogriff",
    "Bush Elephant",
    "Midnight Dragon",
    "Halloween White Ghost Dragon",
    "Dancing Dragon",
    "Gilded Snake",
    "Werewolf",
    "Diamond King Penguin",
    "Golden Chow-Chow",
    "Lavender Dragon",
    "Ice Golem",
    "Queen Bee",
    "Diamond Unicorn",
    "Albino Gorilla",
    "Ninja Monkey",
    "Capricorn",
    "Skele-Rex",
    "Rainbow Dragon",
    "Golden Penguin",
    "Shark Puppy",
    "White Amazon",
    "Phoenix",
    "Unicorn",
    "Field Mouse",
    "Green Butterfly",
    "Golden Hamster",
    "Cuddly Candle",
    "Sunglider",
    "Glormy Leo",
    "Glormy Hound",
    "Shark",
    "Dodo",
    "T-Rex",
    "Fallow Deer",
    "Winged Horse",
    "Owlbear",
    "Diamond Ladybug",
    "Majestic Pony",
    "Cheetah",
    "Leviathan",
    "Golden Rat",
    "Dimension Drifter",
    "Jousting Horse",
    "Diamond Dragon",
    "Octopus",
    "Royal Capuchin Monkey",
    "Naga Dragon",
    "Tree Kangaroo",
    "Candy Hare",
    "Cactus Friend",
    "Goldhorn",
    "Golden Walrus",
    "Firefly",
    "Squid",
    "Chameleon",
    "Astronaut Gorilla",
    "Spinosaurus",
    "Gargoyle",
    "Volcanic Rhino",
    "Black Chow-Chow",
    "Chocolate Chow-Chow",
    "Green-Chested Pheasant",
    "Axolotl",
    "Peacock",
    "Diamond Griffin",
    "Golden Unicorn",
    "Lava Wolf",
    "Alicorn",
    "Ancient Dragon",
    "King Bee",
    "Golden King Penguin",
    "Golden Albatross",
    "Dimorphodon",
    "Criosphinx",
    "Snow Owl",
    "Guardian Lion",
    "Golden Ladybug",
    "Pirate Hermit Crab",
    "Berry Cool Cube",
    "Hawk",
    "Yule Log Dog",
    "Shetland Pony Light Brown",
    "Mushroom Friend",
    "Cerberus",
    "Winter Buck",
    "Princess Capuchin Monkey",
    "Evil Chick",
    "Corn Doggo",
    "Diamond Mahi Mahi",
    "Chimera",
    "Billy Goat",
    "Fleur De Ice",
    "Baku",
    "Golden Dragon",
    "Dire Stag",
    "Maneki-Neko",
    "Robo Dog",
    "Ice Moth Dragon",
    "Scarecrow Crow",
    "Striped Eggy",
    "Blue Betta Fish",
    "Golden Griffin",
    "Rosy Maple Moth",
    "Cobra",
    "Frostclaw",
    "Scarebear",
    "Kraken",
    "Mecha Meow",
    "Kitsune",
    "Dragon",
    "Sunrise Duckling",
    "Halloween Golden Mummy Cat",
    "Dragonfly",
    "Griffin",
    "Lunar Moon Bear",
    "Lunar Gold Tiger",
    "Golden Tortoise Beetle",
    "Dracula Parrot",
    "Metal Ox",
    "Zodiac Minion Chick",
    "Cow",
    "Elephant",
    "Border Collie",
    "Pig",
    "Ring-Tailed Lemur",
    "Goose",
    "Hyena",
    "Shrew",
    "Hare",
    "Giant Anteater",
    "Brown Bear",
    "Mule",
    "Husky",
    "Rhino",
    "Polar Bear",
    "Swan",
    "Reindeer",
    "Evil Rock",
    "Ghost Dog",
    "Leopard Shark",
    "Love Bird",
    "English Sheepdog",
    "Moonpine",
    "Zeopod",
    "Lynx",
    "Musk Ox",
    "Nebula Snake",
    "Blossom Snake",
    "Prism Snake",
    "Cow Calf",
    "Irish Elk",
    "Summer Walrus",
    "Hippo",
    "Great Pyrenees",
    "Moonlight Moth",
    "Starhopper",
    "Singularity Pisces",
    "Singularity Beetle",
    "Longhorn Cow",
    "Marabou Stork",
    "Cassowary",
    "Rat",
    "Nutcracker Squirrel",
    "Kiwi",
    "Basilisk",
    "Sasquatch",
    "Tasmanian Devil",
    "Sea Angel",
    "Halloween Evil Dachshund",
    "Pudding Cat",
    "Feesh",
    "Punk Pony",
    "Steppe Lion",
    "Undead Elk",
    "Bird Of Paradise",
    "Winter Fawn",
    "Goldfish",
    "Koi Carp",
    "Flaming Zebra",
    "Tarsier",
    "Chipmunk",
    "Leopard Cat",
    "Ibex",
    "Ostrich",
    "Gecko",
    "Eggnog Hare",
    "Happy Duckling",
    "Ice Cube",
    "Blue Jay",
    "Weevil",
    "Capuchin Monkey",
    "Emu",
    "Pterodactyl",
    "Woolly Mammoth",
    "Dilophosaurus",
    "Bloodhound",
    "Oryx",
    "Thorny Devil",
    "Gorilla",
    "Merhorse",
    "Moon Rabbit",
    "Ocelot",
    "Australian Kelpie",
    "Ankylosaurus",
    "Scarecrow Horse",
    "Narwhal",
    "Ghost Wolf",
    "Dotted Eggy",
    "Castle Hermit Crab",
    "Seahorse",
    "Black Moon Bear",
    "Halloween White Mummy Cat",
    "Ibis",
    "Woodpecker",
    "Poison Dart Frog",
    "Monkey",
    "Red Fox",
    "Abyssinian Cat",
    "Zebra",
    "Yellow Butterfly",
    "Indian Leopard",
    "Toy Poodle",
    "Orange Betta Fish",
    "Zombie Chick",
    "Shetland Pony Dark Brown",
    "Orangutan",
    "Parakeet",
    "Bunny",
    "Rabbit",
    "Snow Puma",
    "Lunar Tiger",
    "Beaver",
    "Ox",
    "Chicken",
    "Classic Teapot",
    "Robin",
    "Chick",
    "Ratatoskr",
    "Ash Zebra",
    "Hopbop",
    "Maleo Bird",
    "Tasmanian Tiger",
    "Ground Sloth",
    "Ghost",
    "Urchin",
    "Brachiosaurus",
    "Coyote",
    "Garden Snake",
    "Kid Goat",
    "Mongoose",
    "Bali Starling",
    "Stingray",
    "Wolpertinger",
    "Dugong",
    "Walrus",
    "Liger",
    "Cockroach",
    "Malaysian Tapir",
    "Flying Fish",
    "Bullfrog",
    "Bandicoot",
    "Angelfish",
    "Show Pony",
    "Frankenfeline",
    "Bluebottle Fly",
    "Armadillo",
    "Sandfish",
    "Beluga Whale",
    "Mosquito",
    "Sado Mole",
    "Mouse",
    "Piranha",
    "Buffalo",
    "Ant",
    "Otter",
    "Dog",
    "Cat",
    "Blue Dog",
    "Pink Cat",
    "Meerkat",
    "Black Panther",
    "Wild Boar",
    "Capybara",
    "Silly Duck",
    "Drake",
    "Wolf",
    "Mistletroll",
    "Snorgle",
    "Glyptodon",
    "Therapy Dog",
    "Chickatrice",
    "Snow Leopard",
    "Dingo",
    "Canadian Goose",
    "Quokka",
    "2021 Uplift Butterfly",
    "Birthday Butterfly 2024",
    "2022 Uplift Butterfly",
    "Birthday Butterfly 2023",
    "Triceratops",
    "Poodle",
    "Eggnog Dog",
    "Sea Skeleton Panda",
    "Stegosaurus",
    "Rock",
    "Dracula Fish",
    "Eel",
    "Amami Rabbit",
    "Mole",
    "Cute-A-Cabra",
    "Warthog",
    "Dolphin",
    "Crab",
    "Harp Seal",
    "Rodeo Bull",
    "Ermine",
    "Black Marlin",
    "Scarecrow",
    "Lobster",
    "Arctic Tern",
    "Possum",
    "Slug",
    "Snowman",
    "Kirin",
    "Rhino Beetle",
    "Tanuki",
    "Rattlesnake",
    "Gila Monster",
    "Velociraptor",
    "Bat",
    "Halloween Blue Scorpion",
    "Yellow-Lipped Sea Krait",
    "Red Cardinal",
    "Hermit Crab",
    "Arctic Hare",
    "Raccoon",
    "Frogspawn",
    "Mahi Mahi",
    "Banded Palm Civet",
    "Halloween Black Mummy Cat",
    "Angler Fish",
    "Borhyaena Gigantica",
    "Fossa",
    "Tawny Frogmouth",
    "Rock Pigeon",
    "Donkey",
    "Snow Cat",
    "Fennec Fox",
    "Chocolate Labrador",
    "Puma",
    "Camel",
    "Rainbow Rattle",
    "Candy Cannon",
    "Flying Broomstick",
    "Tombstone Ghostify",
    "Egg Stroller",
    "Premium Monkey Box",
    "Golden Gift",
    "Pumpkin",
    "Chinese Lantern",
    "Quad Stroller",
    "Christmas Gift",
    "Hugging Egg",
    "Pet Handler Pro Certificate",
    "Hot Cocoa Stand",
    "Fly A Pet Potion Forever",
    "Ride A Pet Potion Forever",
    "1000 Bucks Silk Bag",
    "Hotdog Stand",
    "Cotton Candy Stand",
    "Lemonade Stand",
    "Classic Trade Stand",
    "Magic House Door",
    "Dylan",
    "Healing Apple",
    "Apple",
    "Cherry-on-Top",
    "Rainbow Maker",
    "Strawberry Shortcake Bat Dragon Backpack",
    "Santa Hat",
    "Ice Cream Cone Hat",
    "Unicorn Horn",
    "Shadow Wings",
    "Angel Wings",
    "Monkey King Crown",
    "Gold Crown",
    "Elf Hat",
    "Pink Cat Ear Headphones",
    "Blue Cat Ear Headphones",
    "Rain Cloud Hat",
    "Pink Heart Glasses",
    "Blue Butterfly Wings",
    "Gold Fairy Crown",
    "Pink Butterfly Wings",
    "Pink Hightops",
    "Gold Tiara",
    "Gold Circle Glasses",
    "Purple Heart Glasses",
    "Founders Crown",
    "Neon Black Scooter",
    "Neon Red Scooter",
    "Neon Blue Scooter",
    "Neon Pink Scooter",
    "Neon White Scooter",
    "Neon Green Scooter",
    "Neon Orange Scooter",
    "Ghost Vehicle",
    "Rocket Sled",
    "Cloud",
    "Super Jetpack",
    "GoKart",
    "Giant Cheetah Mount",
    "Bathtub",
    "Bunny Carriage",
    "Mono-Moped",
    "Horse and Carriage",
    "Enchanted Broomstick",
    "Safari Egg",
    "Jungle Egg",
    "Blue Egg",
    "Farm Egg",
    "Pink Egg",
    "Christmas Egg",
    "Aussie Egg",
    "Easter 2020 Egg",
    "Diamond Egg",
    "Royal Desert Egg",
    "Royal Moon Egg",
    "Golden Egg",
    "Fossil Egg",
    "Ocean Egg",
    "Mythic Egg",
    "Fool Egg",
    "Royal Egg",
    "Woodland Egg",
    "Japan Egg",
    "Southeast Asia Egg",
    "Moon Egg",
    "Danger Egg",
    "Urban Egg",
    "Desert Egg",
    "Garden Egg",
    "Christmas Future Egg",
    "Retired Egg",
    "Zodiac Minion Egg",
    "Pet Egg",
    "Cracked Egg",
    "Sweetheart Rat",
    "Icy Porcupine",
    "Snowy Mammoth",
    "Frozen Penguin",
    "Gaelic Fae",
    "Frostbite Bear",
    "Shiver Wolf",
    "Subzero Scorpion",
    "Clover Cow",
    "Tri-Horned Treehopper",
    "Sakura Spirit",
    "Bakeneko",
    "Kage Crow",
    "Super Saru",
    "Kappakid",
    "Cabbit",
    "Toxic Kaijunior",
    "Scorching Kaijunior",
    "Primal Kaijunior",
    "Kaijunior"
  ]